version: '3.8'

services:
  database:
    container_name: database
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strendor
      MYSQL_USER: strendor
      MYSQL_PASSWORD: secret
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/strendor
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/strendor
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
